name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/example/build
    
    - name: Configure CMake
      shell: bash
      working-directory: $GITHUB_WORKSPACE/example/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: $GITHUB_WORKSPACE/example/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: $GITHUB_WORKSPACE/example/build
      shell: bash
      run: ctest -C $BUILD_TYPE -V
